defaults: &defaults
  adapter: postgresql
  encoding: unicode
  database: doctors
  pool: 5
  username: doctors
  password: p123
  host: localhost

development:
  <<: *defaults

test: &test
  <<: *defaults
  database: userportal_test

